/*
 *   IRC - Internet Relay Chat, src/version.c
 *   Copyright (C) 1990 Chelsea Ashley Dyerman
 *
 *   This program is free software; you can redistribute it and/or modify
 *   it under the terms of the GNU General Public License as published by
 *   the Free Software Foundation; either version 1, or (at your option)
 *   any later version.
 *
 *   This program is distributed in the hope that it will be useful,
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *   GNU General Public License for more details.
 *
 *   You should have received a copy of the GNU General Public License
 *   along with this program; if not, write to the Free Software
 *   Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
 */

/*
 * This file is generated by version.c.SH. Any changes made will go away.
 */

#include "patchlevel.h"
#include "serno.h"

char *generation = "1";
char *creation = "Thu May 24 2001 at 05:33:30 BST";
char *platform = "OpenVMS 7.2/Alpha";
char *version = PATCHLEVEL;
char *serno = SERIALNUM;

char *infotext[] =
{
  "IRC --",
  "Based on the original code written by Jarkko Oikarinen",
  "Copyright 1988, 1989, 1990, 1991 University of Oulu, Computing Center",
  "",
  "This program is free software; you can redistribute it and/or",
  "modify it under the terms of the GNU General Public License as",
  "published by the Free Software Foundation; either version 1, or",
  "(at your option) any later version.",
  "",
  " ",
  "The hybrid team is a group of ircd coders who were frustrated",
  "with the instability and all-out dirtiness of the EFnet ircd's",
  "available. hybrid is the name for the collective efforts of a group",
  "of people, all of us.",
  " ",
  "Anyone is welcome to contribute to this effort.  You are encouraged",
  "to participate in the Hybrid mailing list.  To subscribe to the",
  "Hybrid List, send email to listmanager@the-project.org with the",
  "subject subscribe hybrid.",
  " ",
  "The core team as, of this major release:",
  "A1kmm, Andrew Miller <a1kmm@mware.virtualave.net> ",
  "adrian, Adrian Chadd <adrian@creative.net.au>",
  "AndroSyn, Aaron Sethman <androsyn@ratbox.org>",
  "bysin, Ben Kittridge <bkittridge@cfl.rr.com>",
  "cosine, Patrick Alken <wnder@uwns.underworld.net>",
  "David-T, David Taylor <davidt@yadt.co.uk>",
  "desrt, Ryan Lortie <desertangel@mindless.com>",
  "Dianora, Diane Bruce <db@db.net>",
  "fl_, Lee Hardy <leeh@shagged.org>",
  "Habeeb, David Supuran <habeeb@cfl.rr.com>",
  "is, Edward Brocklesby <ejb@leguin.org.uk>",
  "isomer, Perry Lorier <perry@coders.net>",
  "madmax, Paul Lomax <madmax@efnet.org>",
  "Neph|l|m, Adel Mezibra <adel@cybercable.fr>",
  "pro, Bill Jonus <proggy@earthling.net>",
  "Rodder, Jon Lusky <lusky@blown.net>",
  "toot, Toby Verrall <to7@antipope.fsnet.co.uk>",
  "Wohali, Joan Touzet <joant@ieee.org>",
  " ",
  "The following people have contributed blood, sweat, and/or code to",
  "this release of hybrid, in nick alphabetical order:",
  " ",
  "_k9_, Jeremy Chadwick <jdc@best.net>",
  "einride, anon <einride@einride.net>",
  "Hwy101, Walter Campbell <wcampbel@botbay.net>",
  "kre, Dinko Korunic <kreator@fly.srk.fer.hr>",
  "LarZ, Matthew Ramsey <mjr@blackened.com>",
  "orabidoo, Roger Espel Llima <espel@unix.bigots.org>",
  "Riedel, Dennis Vink, <vink@vuurwerk.nl>",
  "Seaner, Sean McVeigh <sdlmcvei@uwaterloo.ca>",
  "spookey, David Colburn <spookey@spookey.org>",
  "vx0, Mark Miller <mark@vx0.net>",
  "WintrHawk, Jake Khuon <khuon@GCtr.Net>",
  "vulture, Sean Stanek <vulture@cs.iastate.edu>",
  "zb^3, Alfred Perlstein <alfred@freebsd.org>",
  " ",
  "Others are welcome. Always.  And if we left anyone off the above list,",
  "be sure to let us know that too.  Many others have contributed to",
  "previous versions of this ircd and it's ancestors, too many to list",
  "here.",
  " ",
  "Send bug fixes/complaints/rotten tomatoes to ircd-hybrid@the-project.org.",
  "http://bugs.efnow.net may be worth a visit first.",
  "",
  0,
};
