# MMS/MMK Makefile for OpenVMS
# Copyright (c) 2001 Edward Brocklesby

CC=	CC
CFLAGS=	/STANDARD=ISOC94
LDFLAGS=

ALL : FIXKLINES,CONVERTCONF

FIXKLINES : FIXKLINES.C
	CC FIXKLINES
	LINK FIXKLINES

CONVERTCONF : CONVERTCONF.C
	CC CONVERTCONF
	LINK CONVERTCONF

CLEAN : 
	DELETE *.OBJ;*
	DELETE *.EXE;*
